### ISSUE TITLE
Doesn't work in Ruby 2.2

### ISSUE THREAD

**Issue by mariotux** [yabeda-rb/yabeda#14]
I tried to use the yabeda gems and after bundle install when I am going to run the rails s, I have this error.

`option_names': undefined method `dry_initializer' for Yabeda::Counter:Class (NoMethodError)

I am trying to use them in a rails 4.2 project with ruby 2.2.1

Can you help me? thank you.

**Comment by Envek** [comment]
Thanks for confirming that it doesn't work in Ruby 2.2!
